---
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  FinalNewline:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
  RightTrim:
    enabled: true
    enforced_style: '-'
  SelfClosingTag:
    enabled: true
    enforced_style: 'never'
  SpaceInHtmlTag:
    exclude:
  SpaceAroundErbTag:
    enabled: true
  HardCodedString:
    enabled: true
    exclude:
      - '*app/views/**'
