version: '3'
services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DEV_PASS}
  web:
    build: .
    command: ./scripts/docker-entrypoint.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
    ports:
      - "1234:1234"
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - PROXY_URL=http://host.docker.internal:8888
      - RAILS_DEV_DB_PASS=${DEV_PASS}
      - OAUTH_DEBUG
      - ENV_TYPE=development
    stdin_open: true
    tty: true # Allow interactive byebug sessions.
    healthcheck:
      test: curl --fail -s http://localhost:3000/
      interval: 20s
      timeout: 180s
      retries: 10
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
volumes:
  pg-data:
  node_modules:
