version: "3.5"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    networks:
      default:
        aliases:
          - curriculum.teachcomputing.rpfdev.com
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DEV_PASS}
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    env_file:
      - .env

  web:
    build: .
    command: ./scripts/docker-entrypoint.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
      - bundle:/usr/local/bundle
    ports:
      - "1234:1234"
      - "1235:1235"
      - "3000:3000"
    depends_on:
      - db
      - redis
      - webpack
      - docker-host
    environment:
      - PROXY_URL=http://host.docker.internal:8888
      - RAILS_DEV_DB_PASS=${DEV_PASS}
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - DOCKER_LOGS=true
    stdin_open: true
    tty: true # Allow interactive byebug sessions
    restart: unless-stopped

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
      - bundle:/usr/local/bundle
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack

volumes:
  bundle:
  pg-data:
  node_modules:
