version: "3.5"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: unless-stopped
    networks:
      default:
        aliases:
          - curriculum.teachcomputing.rpfdev.com

  db:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - redis
      - web
    env_file:
      - ${ENV_FILE:-.env.defaults}
    restart: unless-stopped

  web:
    build: .
    command: ./scripts/docker-entrypoint.sh
    init: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules # ensures we retain node_modules from docker build
      - bundle:/usr/local/bundle
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh:/root/.ssh
      - bash_history:/root/.bash_history
    ports:
      - "1234:1234"
      - "1235:1235"
      - "3000:3000"
    depends_on:
      - db
      - redis
      - docker-host
      - webpack
    environment:
      - RAILS_DEV_DB_PASS=password
      - WEBPACKER_DEV_SERVER_HOST=webpack
    stdin_open: true
    tty: true # Allow interactive byebug sessions
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/healthcheck" ]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 45s
    env_file:
      - ${ENV_FILE:-.env.defaults}

  webpack:
    build: .
    command: ./scripts/webpack-docker-entrypoint.sh
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    restart: unless-stopped

volumes:
  bundle: null
  pg-data: null
  node_modules: null
  ssh: null
  bash_history: null
