version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ncce_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - ncce-bundle-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: ncce-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or npm in some other way
      - restore_cache:
          keys:
            - ncce-npm-{{ checksum "npm.lock" }}

      - run:
          name: Npm Install
          command: npm install --cache-folder ~/.cache/npm

      # Store npm / webpacker cache
      - save_cache:
          key: ncce-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # Run rspec
      - run:
          name: Run rspec
          command: |
            bundle exec rspec
