version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.2.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: vendor/bundle
          CREDENTIALS_ENV: test
          DB_HOST: 127.0.0.1
          PGHOST: 127.0.0.1
          PGUSER: ncce_test
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ncce_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - ncce-bundle-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: ncce-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: |
            mkdir ~/rspec
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml

      - store_test_results:
          path: ~/rspec

      - store_artifacts:
          path: coverage

      - store_artifacts:
          path: ../tmp/screenshots
          destination: screenshots

      - run:
          name: Run brakeman
          command: |
            bundle exec brakeman -q -i config/brakeman.ignore --no-summary


  lighthouse:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          MANDRILL_SMTP_USERNAME: fake
          MANDRILL_API_KEY: fake
          STEM_OAUTH_SITE: fake
          STEM_OAUTH_AUTH_URL: fake
          STEM_OAUTH_ACCESS_TOKEN_URL: fake
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install Lighthouse
          command: sudo npm install -g @lhci/cli@0.8.x
      - run:
          name: Run Lighthouse
          command: lhci autorun

workflows:
  version: 2
  test:
    jobs:
      - test
      - lighthouse
